PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
INSERT INTO "quizzes" VALUES(1,'Python quiz','python','Is python your main programing language? Well this is for you.');
INSERT INTO "quizzes" VALUES(2,'C++ quiz','cplusplus','Goog in C++? Try this.');
INSERT INTO "quizzes" VALUES(3,'Java quiz','quiz','Feeling good in java? Proove it!');
INSERT INTO "questions" VALUES(1,'Which of the following data types is not supported in python?',1);
INSERT INTO "questions" VALUES(2,'What is the output of print str[2:] if str = ''Hello World!''?',1);
INSERT INTO "questions" VALUES(3,'What is the output of print tinylist * 2 if tinylist = [123, ''john'']?',1);
INSERT INTO "questions" VALUES(4,'Which of the following function convert a String to a tuple in python?',1);
INSERT INTO "questions" VALUES(5,' Which of the following operator in python performs the division on operands where the result is the quotient in which the digits after the decimal point are removed?',1);
INSERT INTO "questions" VALUES(6,'Which of the following function randomizes the items of a list in place?',1);
INSERT INTO "questions" VALUES(7,'Which of the following function checks in a string that all characters are numeric?',1);
INSERT INTO "questions" VALUES(8,'Which of the following function checks in a string that all characters are decimal?',1);
INSERT INTO "questions" VALUES(9,'What is the output of len([1, 2, 3])?',1);
INSERT INTO "questions" VALUES(10,'What is the following function inserts an object at given index in a list?',1);
INSERT INTO "questions" VALUES(11,'Which of the following is correct about Python?',1);
INSERT INTO "questions" VALUES(12,'What is the output of print str * 2 if str = ''Hello World!''?',1);
INSERT INTO "questions" VALUES(13,'Which of the following function convert an integer to an unicode character in python?',1);
INSERT INTO "questions" VALUES(14,'Which of the following statement causes the loop to skip the remainder of its body and immediately retest its condition prior to reiterating?',1);
INSERT INTO "questions" VALUES(15,'Which of the following function checks in a string that all characters are in uppercase?',1);
INSERT INTO "questions" VALUES(16,'What is the output of for x in [1, 2, 3]: print x?',1);
INSERT INTO "questions" VALUES(17,'What is the following function returns the lowest index in list that obj appears?',1);
INSERT INTO "questions" VALUES(18,'Which of the following environment variable for Python is used in Windows to instruct Python to find the first case-insensitive match in an import statement?',1);
INSERT INTO "questions" VALUES(19,'Which of the following operator in python performs exponential (power) calculation on operands?',1);
INSERT INTO "questions" VALUES(20,'Which of the following function sets the integer starting value used in generating random numbers?',1);
INSERT INTO "questions" VALUES(21,'The following operator can be used to calculate the value of one number raised to another.',2);
INSERT INTO "questions" VALUES(22,'The pointer which stores always the current active object address is __',2);
INSERT INTO "questions" VALUES(23,'HAS-A relationship between the classes is shown through.',2);
INSERT INTO "questions" VALUES(24,'Identify the C++ compiler of Linux',2);
INSERT INTO "questions" VALUES(25,'One of the following is true for an inline function',2);
INSERT INTO "questions" VALUES(26,'With respective to streams >> (operator) is called as',2);
INSERT INTO "questions" VALUES(27,'Special symbol permitted with in the identifier name.',2);
INSERT INTO "questions" VALUES(28,'Choose the operator which cannot be overloaded.',2);
INSERT INTO "questions" VALUES(29,'Choose the respective delete operator usage for the expression ‘ptr=new int[100]’.',2);
INSERT INTO "questions" VALUES(30,'Operators sizeof and ?',2);
INSERT INTO "questions" VALUES(31,'Escape sequence character ''\0'' occupies __ amount of memory.',2);
INSERT INTO "questions" VALUES(32,'Following is the invalid inclusion of a file to the current program. Identify it',2);
INSERT INTO "questions" VALUES(33,'A trigraph character begins with',2);
INSERT INTO "questions" VALUES(34,' By default the members of the structure are',2);
INSERT INTO "questions" VALUES(35,'The following operator can be used to calculate the value of one number raised to another.',2);
INSERT INTO "questions" VALUES(36,'How can we make an class act as an interface in C++?',2);
INSERT INTO "questions" VALUES(37,'An exception is __',2);
INSERT INTO "questions" VALUES(38,'C++ does not supports the following',2);
INSERT INTO "questions" VALUES(39,'Which data type can be used to hold a wide character in C++?',2);
INSERT INTO "questions" VALUES(40,' A protected member of the class in accessible in',2);
INSERT INTO "questions" VALUES(41,'What is the size of char variable?',3);
INSERT INTO "questions" VALUES(42,'What is the default value of long variable?',3);
INSERT INTO "questions" VALUES(43,'Which of the following is true about String?',3);
INSERT INTO "questions" VALUES(44,'What is an Interface?',3);
INSERT INTO "questions" VALUES(45,'What is static block?',3);
INSERT INTO "questions" VALUES(46,'What is NullPointerException?',3);
INSERT INTO "questions" VALUES(47,'Which is the way in which a thread can enter the waiting state?',3);
INSERT INTO "questions" VALUES(48,'Which method must be implemented by all threads?',3);
INSERT INTO "questions" VALUES(49,'What of the following is the default value of a local variable?',3);
INSERT INTO "questions" VALUES(50,'Method Overloading is an example of',3);
INSERT INTO "questions" VALUES(51,'What invokes a thread''s run() method?',3);
INSERT INTO "questions" VALUES(52,'What is the default value of Object variable?',3);
INSERT INTO "questions" VALUES(53,'What is instance variable?',3);
INSERT INTO "questions" VALUES(54,'What is TreeSet Interface?',3);
INSERT INTO "questions" VALUES(55,'Static binding uses which information for binding?',3);
INSERT INTO "questions" VALUES(56,'When finally block gets executed?',3);
INSERT INTO "questions" VALUES(57,'Which of the following is not a keyword in java?',3);
INSERT INTO "questions" VALUES(58,'Which of the following is true about protected access modifier?',3);
INSERT INTO "questions" VALUES(59,'What is an immutable object?',3);
INSERT INTO "questions" VALUES(60,'What is Serialization?',3);

INSERT INTO "answers" VALUES(1,'Tuple',1,0);
INSERT INTO "answers" VALUES(2,'Dictionary',1,0);
INSERT INTO "answers" VALUES(3,'Generics',1,1);
INSERT INTO "answers" VALUES(4,'List',1,0);
INSERT INTO "answers" VALUES(5,'llo World!',2,1);
INSERT INTO "answers" VALUES(6,'H',2,0);
INSERT INTO "answers" VALUES(7,'llo',2,0);
INSERT INTO "answers" VALUES(8,'None of the above.',2,0);
INSERT INTO "answers" VALUES(9,'[123, ''john'', 123, ''john'']',3,1);
INSERT INTO "answers" VALUES(10,'[123, ''john''] * 2',3,0);
INSERT INTO "answers" VALUES(11,'Error',3,0);
INSERT INTO "answers" VALUES(12,'None of the above.',3,0);
INSERT INTO "answers" VALUES(13,'repr(x)',4,0);
INSERT INTO "answers" VALUES(14,'eval(str)',4,0);
INSERT INTO "answers" VALUES(15,'tuple(s)',4,1);
INSERT INTO "answers" VALUES(16,'list(s)',4,0);
INSERT INTO "answers" VALUES(17,' **',5,0);
INSERT INTO "answers" VALUES(18,' //',5,1);
INSERT INTO "answers" VALUES(19,'is',5,0);
INSERT INTO "answers" VALUES(20,' not in',5,0);
INSERT INTO "answers" VALUES(21,'shuffle(lst)',6,1);
INSERT INTO "answers" VALUES(22,'capitalize()',6,0);
INSERT INTO "answers" VALUES(23,'isalnum()',6,0);
INSERT INTO "answers" VALUES(24,' isdigit()',6,0);
INSERT INTO "answers" VALUES(25,'islower()',7,0);
INSERT INTO "answers" VALUES(26,'isnumeric()',7,1);
INSERT INTO "answers" VALUES(27,'isspace()',7,0);
INSERT INTO "answers" VALUES(28,' istitle()',7,0);
INSERT INTO "answers" VALUES(29,'upper()',8,0);
INSERT INTO "answers" VALUES(30,'isdecimal()',8,1);
INSERT INTO "answers" VALUES(31,'swapcase()',8,0);
INSERT INTO "answers" VALUES(32,'title()',8,0);
INSERT INTO "answers" VALUES(33,'1',9,0);
INSERT INTO "answers" VALUES(34,'2',9,0);
INSERT INTO "answers" VALUES(35,'3',9,1);
INSERT INTO "answers" VALUES(36,'4',9,0);
INSERT INTO "answers" VALUES(37,'list.index(obj)',10,0);
INSERT INTO "answers" VALUES(38,'list.insert(index, obj)',10,1);
INSERT INTO "answers" VALUES(39,'list.pop(obj=list[-1])',10,0);
INSERT INTO "answers" VALUES(40,'list.remove(obj)',10,0);
INSERT INTO "answers" VALUES(41,'Python is a high-level, interpreted, interactive and object-oriented scripting language.',11,0);
INSERT INTO "answers" VALUES(42,'Python is designed to be highly readable.',11,0);
INSERT INTO "answers" VALUES(43,'It uses English keywords frequently where as other languages use punctuation, and it has fewer syntactical constructions than other languages.',11,0);
INSERT INTO "answers" VALUES(44,' All of the above.',11,1);
INSERT INTO "answers" VALUES(45,'Hello World!Hello World!',12,1);
INSERT INTO "answers" VALUES(46,'Hello World! * 2',12,0);
INSERT INTO "answers" VALUES(47,'Hello World!',12,0);
INSERT INTO "answers" VALUES(48,'None of the above.',12,0);
INSERT INTO "answers" VALUES(49,'unichr(x)',13,1);
INSERT INTO "answers" VALUES(50,'ord(x)',13,0);
INSERT INTO "answers" VALUES(51,'hex(x)',13,0);
INSERT INTO "answers" VALUES(52,'oct(x)',13,0);
INSERT INTO "answers" VALUES(53,'break',14,0);
INSERT INTO "answers" VALUES(54,'continue',14,1);
INSERT INTO "answers" VALUES(55,'pass',14,0);
INSERT INTO "answers" VALUES(56,'None of the above.',14,0);
INSERT INTO "answers" VALUES(57,'isupper()',15,1);
INSERT INTO "answers" VALUES(58,' join(seq)',15,0);
INSERT INTO "answers" VALUES(59,' len(string)',15,0);
INSERT INTO "answers" VALUES(60,'ljust(width[, fillchar])',15,0);
INSERT INTO "answers" VALUES(61,'x x x',16,0);
INSERT INTO "answers" VALUES(62,' 1 2 3',16,1);
INSERT INTO "answers" VALUES(63,'Error',16,0);
INSERT INTO "answers" VALUES(64,'None of the above.',16,0);
INSERT INTO "answers" VALUES(65,'list.index(obj)',17,1);
INSERT INTO "answers" VALUES(66,' list.insert(index, obj)',17,0);
INSERT INTO "answers" VALUES(67,'list.pop(obj=list[-1])',17,0);
INSERT INTO "answers" VALUES(68,' list.remove(obj)',17,0);
INSERT INTO "answers" VALUES(69,' PYTHONPATH',18,0);
INSERT INTO "answers" VALUES(70,'PYTHONSTARTUP',18,0);
INSERT INTO "answers" VALUES(71,'PYTHONCASEOK',18,1);
INSERT INTO "answers" VALUES(72,'PYTHONHOME',18,0);
INSERT INTO "answers" VALUES(73,' **',19,1);
INSERT INTO "answers" VALUES(74,'//',19,0);
INSERT INTO "answers" VALUES(75,' is',19,0);
INSERT INTO "answers" VALUES(76,'not in',19,0);
INSERT INTO "answers" VALUES(77,'choice(seq)',20,0);
INSERT INTO "answers" VALUES(78,'randrange ([start,] stop [,step])',20,0);
INSERT INTO "answers" VALUES(79,'random()',20,0);
INSERT INTO "answers" VALUES(80,'seed([x])',20,1);
INSERT INTO "answers" VALUES(81,' ^',21,0);
INSERT INTO "answers" VALUES(82,'**',21,0);
INSERT INTO "answers" VALUES(83,'^^',21,0);
INSERT INTO "answers" VALUES(84,'None of the above',21,1);
INSERT INTO "answers" VALUES(85,'auto_ptr',22,0);
INSERT INTO "answers" VALUES(86,'this',22,1);
INSERT INTO "answers" VALUES(87,'p',22,0);
INSERT INTO "answers" VALUES(88,'none of the above.',22,0);
INSERT INTO "answers" VALUES(89,'Inheritance',23,0);
INSERT INTO "answers" VALUES(90,'Container classes',23,1);
INSERT INTO "answers" VALUES(91,'Polymorphism',23,0);
INSERT INTO "answers" VALUES(92,'None of the above.',23,0);
INSERT INTO "answers" VALUES(93,' cpp',24,0);
INSERT INTO "answers" VALUES(94,' g++',24,1);
INSERT INTO "answers" VALUES(95,'Borland',24,0);
INSERT INTO "answers" VALUES(96,' vc++',24,0);
INSERT INTO "answers" VALUES(97,' It executes faster as it is treated as a macro internally',25,0);
INSERT INTO "answers" VALUES(98,'It executes faster because it priority is more than normal function',25,0);
INSERT INTO "answers" VALUES(99,'It doesn’t executes faster compared to a normal function',25,1);
INSERT INTO "answers" VALUES(100,'None of the above holds true for an inline function',25,0);
INSERT INTO "answers" VALUES(101,'Insertion operator',26,0);
INSERT INTO "answers" VALUES(102,'Extraction operator',26,1);
INSERT INTO "answers" VALUES(103,'Right shift operator',26,0);
INSERT INTO "answers" VALUES(104,'Left shift operator',26,0);
INSERT INTO "answers" VALUES(105,'$',27,0);
INSERT INTO "answers" VALUES(106,' @',27,0);
INSERT INTO "answers" VALUES(107,'_',27,1);
INSERT INTO "answers" VALUES(108,'.',27,0);
INSERT INTO "answers" VALUES(109,'/',28,0);
INSERT INTO "answers" VALUES(110,'()',28,0);
INSERT INTO "answers" VALUES(111,'::',28,1);
INSERT INTO "answers" VALUES(112,'%',28,0);
INSERT INTO "answers" VALUES(113,' delete ptr;',29,0);
INSERT INTO "answers" VALUES(114,'delete ptr[];',29,0);
INSERT INTO "answers" VALUES(115,' delete[] ptr;',29,1);
INSERT INTO "answers" VALUES(116,' []delete ptr;',29,0);
INSERT INTO "answers" VALUES(117,'Both can be overloaded',30,0);
INSERT INTO "answers" VALUES(118,'Both cannot be overloaded',30,1);
INSERT INTO "answers" VALUES(119,'Only sizeof can be overloaded',30,0);
INSERT INTO "answers" VALUES(120,'Only ?: can be overloaded',30,0);
INSERT INTO "answers" VALUES(121,' 0',31,0);
INSERT INTO "answers" VALUES(122,'1',31,1);
INSERT INTO "answers" VALUES(123,'2',31,0);
INSERT INTO "answers" VALUES(124,'3',31,0);
INSERT INTO "answers" VALUES(125,'#include <file>',32,0);
INSERT INTO "answers" VALUES(126,'#include "file"',32,0);
INSERT INTO "answers" VALUES(127,'#include < file',32,1);
INSERT INTO "answers" VALUES(128,'All of the above are invalid',32,0);
INSERT INTO "answers" VALUES(129,'#',33,0);
INSERT INTO "answers" VALUES(130,'##',33,0);
INSERT INTO "answers" VALUES(131,'?',33,1);
INSERT INTO "answers" VALUES(132,'??',33,0);
INSERT INTO "answers" VALUES(133,'private',34,0);
INSERT INTO "answers" VALUES(134,'protected',34,0);
INSERT INTO "answers" VALUES(135,'public',34,1);
INSERT INTO "answers" VALUES(136,'Access specifiers not applicable for structures.',34,0);
INSERT INTO "answers" VALUES(137,'^',35,0);
INSERT INTO "answers" VALUES(138,'**',35,0);
INSERT INTO "answers" VALUES(139,'^^',35,0);
INSERT INTO "answers" VALUES(140,'None of the above',35,1);
INSERT INTO "answers" VALUES(141,'By only providing all the functions as virtual functions in the class.',36,1);
INSERT INTO "answers" VALUES(142,'Defining the class following with the keyword virtual',36,0);
INSERT INTO "answers" VALUES(143,'Defining the class following with the keyword interface',36,0);
INSERT INTO "answers" VALUES(144,'Defining the class following with the keyword abstract',36,0);
INSERT INTO "answers" VALUES(145,'Runtime error',37,1);
INSERT INTO "answers" VALUES(146,'Compile time error',37,0);
INSERT INTO "answers" VALUES(147,'Logical error',37,0);
INSERT INTO "answers" VALUES(148,'None of the above',37,0);
INSERT INTO "answers" VALUES(149,'Multilevel inheritance',38,0);
INSERT INTO "answers" VALUES(150,'Hierarchical inheritance',38,0);
INSERT INTO "answers" VALUES(151,'Hybrid inheritance',38,1);
INSERT INTO "answers" VALUES(152,'None of the above.',38,0);
INSERT INTO "answers" VALUES(153,'unsigned char;',39,0);
INSERT INTO "answers" VALUES(154,'int',39,0);
INSERT INTO "answers" VALUES(155,'wchar_t',39,1);
INSERT INTO "answers" VALUES(156,'none of the above.',39,0);
INSERT INTO "answers" VALUES(157,'Only same class',40,0);
INSERT INTO "answers" VALUES(158,'Same class and derived class',40,1);
INSERT INTO "answers" VALUES(159,'Outside the class',40,0);
INSERT INTO "answers" VALUES(160,'None of the above.',40,0);
INSERT INTO "answers" VALUES(161,'8 bit',41,0);
INSERT INTO "answers" VALUES(162,'16 bit',41,1);
INSERT INTO "answers" VALUES(163,'32 bit',41,0);
INSERT INTO "answers" VALUES(164,' 64 bit',41,0);
INSERT INTO "answers" VALUES(165,'0',42,0);
INSERT INTO "answers" VALUES(166,'0.0',42,0);
INSERT INTO "answers" VALUES(167,'0L ',42,1);
INSERT INTO "answers" VALUES(168,'Not defined',42,0);
INSERT INTO "answers" VALUES(169,'String is mutable.',43,0);
INSERT INTO "answers" VALUES(170,'String is immutable.',43,1);
INSERT INTO "answers" VALUES(171,'String is a data type.',43,0);
INSERT INTO "answers" VALUES(172,'None of the above.',43,0);
INSERT INTO "answers" VALUES(173,' An interface is a collection of abstract methods.',44,0);
INSERT INTO "answers" VALUES(174,'Interface is an abstract class.',44,1);
INSERT INTO "answers" VALUES(175,'interface is an concrete class. ',44,0);
INSERT INTO "answers" VALUES(176,'None of the above
',44,0);
INSERT INTO "answers" VALUES(177,'It is used to create syncronized code.',45,0);
INSERT INTO "answers" VALUES(178,'There is no such block.',45,0);
INSERT INTO "answers" VALUES(179,' It is used to initialize the static data member., It is excuted before main method at the time of class loading. ',45,1);
INSERT INTO "answers" VALUES(180,'None of the above',45,0);
INSERT INTO "answers" VALUES(181,'A NullPointerException is thrown when calling the instance method of a null object or modifying/accessing field of a null object.',46,1);
INSERT INTO "answers" VALUES(182,'A NullPointerException is thrown when object is set as null',46,0);
INSERT INTO "answers" VALUES(183,'A NullPointerException is thrown when object property is set as null.',46,0);
INSERT INTO "answers" VALUES(184,'None of the above',46,0);
INSERT INTO "answers" VALUES(185,'Invoke its sleep() method.',47,0);
INSERT INTO "answers" VALUES(186,'invoke object''s wait method.',47,0);
INSERT INTO "answers" VALUES(187,'Invoke its suspend() method.',47,0);
INSERT INTO "answers" VALUES(188,'All of the above.',47,1);
INSERT INTO "answers" VALUES(189,'wait()',48,0);
INSERT INTO "answers" VALUES(190,'start()',48,0);
INSERT INTO "answers" VALUES(191,'stop()',48,0);
INSERT INTO "answers" VALUES(192,' run()',48,1);
INSERT INTO "answers" VALUES(193,'Null',49,0);
INSERT INTO "answers" VALUES(194,'0',49,0);
INSERT INTO "answers" VALUES(195,'Depends upon the type of variable',49,0);
INSERT INTO "answers" VALUES(196,'Not assigned',49,1);
INSERT INTO "answers" VALUES(197,'Static Binding.',50,1);
INSERT INTO "answers" VALUES(198,'Dynamic Binding.',50,0);
INSERT INTO "answers" VALUES(199,'Both of the above.',50,0);
INSERT INTO "answers" VALUES(200,'None of the above.',50,0);
INSERT INTO "answers" VALUES(201,'JVM invokes the thread''s run() method when the thread is initially executed',51,1);
INSERT INTO "answers" VALUES(202,' Main application running the thread.',51,0);
INSERT INTO "answers" VALUES(203,'start() method of the thread class.',51,0);
INSERT INTO "answers" VALUES(204,'None of the above.',51,0);
INSERT INTO "answers" VALUES(205,'Undefined',52,0);
INSERT INTO "answers" VALUES(206,'0',52,0);
INSERT INTO "answers" VALUES(207,'Null ',52,1);
INSERT INTO "answers" VALUES(208,' not defined',52,0);
INSERT INTO "answers" VALUES(209,'Instance variables are static variables within a class but outside any method.',53,0);
INSERT INTO "answers" VALUES(210,'Instance variables are variables defined inside methods, constructors or blocks.',53,0);
INSERT INTO "answers" VALUES(211,'nstance variables are variables within a class but outside any method. ',53,1);
INSERT INTO "answers" VALUES(212,'None of the above.',53,0);
INSERT INTO "answers" VALUES(213,'It is a Set implemented when we want elements in a tree based order.',54,0);
INSERT INTO "answers" VALUES(214,'It is a Set implemented when we want elements in a sorted order. ',54,1);
INSERT INTO "answers" VALUES(215,'It is a Set implemented when we want elements in a binary tree format.',54,0);
INSERT INTO "answers" VALUES(216,'It is a Set implemented when we want elements in a hiearchical order.',54,0);
INSERT INTO "answers" VALUES(217,'type. ',55,1);
INSERT INTO "answers" VALUES(218,'object.',55,0);
INSERT INTO "answers" VALUES(219,'Both of the above.',55,0);
INSERT INTO "answers" VALUES(220,'None of the above.',55,0);
INSERT INTO "answers" VALUES(221,'Always when try block get executed, no matter exception occured or not. ',56,1);
INSERT INTO "answers" VALUES(222,'Always when a method get executed, no matter exception occured or not.',56,0);
INSERT INTO "answers" VALUES(223,'Always when a try block get executed, if exception do not occur.',56,0);
INSERT INTO "answers" VALUES(224,'Only when exception occurs in try block code.',56,0);
INSERT INTO "answers" VALUES(225,'Static',57,0);
INSERT INTO "answers" VALUES(226,'Boolean',57,1);
INSERT INTO "answers" VALUES(227,'Void',57,0);
INSERT INTO "answers" VALUES(228,' Private',57,1);
INSERT INTO "answers" VALUES(229,'Variables, methods and constructors which are declared protected can be accessed by any class.',58,0);
INSERT INTO "answers" VALUES(230,'Variables, methods and constructors which are declared protected can be accessed by any class lying in same package.',58,0);
INSERT INTO "answers" VALUES(231,'Variables, methods and constructors which are declared protected in the superclass can be accessed only by its child class. ',58,1);
INSERT INTO "answers" VALUES(232,'None of the above.',58,0);
INSERT INTO "answers" VALUES(233,'An immutable object can be changed once it is created.',59,0);
INSERT INTO "answers" VALUES(234,'An immutable object can''t be changed once it is created.',59,1);
INSERT INTO "answers" VALUES(235,'An immutable object is an instance of an abstract class.',59,0);
INSERT INTO "answers" VALUES(236,'None of the above.',59,0);
INSERT INTO "answers" VALUES(237,'Serialization is the process of writing the state of an object to another object.',60,0);
INSERT INTO "answers" VALUES(238,'Serialization is the process of writing the state of an object to a byte stream.',60,1);
INSERT INTO "answers" VALUES(239,'Both of the above.',60,0);
INSERT INTO "answers" VALUES(240,'None of the above.',60,0);
COMMIT;
